### ISSUE TITLE
Description is a reserved name

### ISSUE THREAD

**Issue by tapz** [Cclleemm/ProductTour#16]
Xcode warns about this property because NSObject already contains a function called "description". I really suggest changing the name to "desc" or something else.

CRBubble.h:34
@property (nonatomic, strong) NSString *description;

**Comment by Cclleemm** [comment]
Hello,
How do you download the code ? With cocoa pods ?

**Comment by tapz** [comment]
Yes, with CocoaPods. What difference does that make?

**Comment by Cclleemm** [comment]
Sorry, pod was not up to date... Now it's good, you can get it (version 0.0.2) updating your code with CocoaPods.

**Comment by Cclleemm** [comment]
Does it work?
